### PR TITLE
LRHU-12345 Test

### PR DESCRIPTION
**Pull request by lipusz**
Hi Ricsi,

I'm sending this PR to you to test what you've learned so far. Here the tasks I'd like you to complete.

**The end goal is to have my changes in your `master` branch and pushed to your `origin` after altering them a bit**:
* My commit lipusz@da9ca71 should be the first in the order
* My last commit (lipusz@2b7d5f1) should be fixed-up into the commit of "LRHU-12345 Add new file" under that commit message
* There is a typo in the commit message of the the second commit (lipusz@f08700b): please fix it
* Do not use the "Merge this Pull Request" button

Here are some hints about what you'll need to do/use:
* checkout
* fetch
* interactive rebase
* push

Feel free to ask me if you have questions. Let me know when you're done (close this PR).

Good luck! :+1: 
-
Tibi

### CODE REVIEW

**Comment by lipusz** [comment]
Hey Ricsi,

Please try to complete this by this Friday. Thanks!

@benkorichard

**Comment by lipusz** [comment]
Hi @benkorichard 

Any news on this?

**Comment by benkorichard** [comment]
Hi @lipusz 
Sorry for the delayed answer. It's completed.

**Comment by lipusz** [comment]
Almost :smirk: 

>My commit lipusz/git-training@da9ca71 should be the first in the order

That commit is currently the last one in your master branch. Maybe you forgot to move that line when doing the interactive rebase.

But I consider it complete. :+1: 

Good luck with using git and feel free to reach me if you have questions!

Regards,
Tibi

@benkorichard

**Pull request closed without merging**
